Stricter & safer handling of Python exceptions raised in PyCLIF C++ (`std::function`) callbacks.
This is the main CL for the cleanup work tracked under b/284164589.

**Please request a rollback only as a last resort**, to buy time for working out a forward fix.

The PyCLIF callback behavior before this CL was obviously and evidently (b/284164589) very error prone. It was also critically blocking the go/pyclif_pybind11_fusion work.

Options for fixing forward:

0. In the fairly likely event that submitting this CL exposes a latent bug elsewhere: Please fix.

1. If Python exceptions are expected, the recommended approach for handling them is to use `absl::Status` / `absl::StatusOr` as the callback return value. Python exceptions are automatically converted to `absl::Status` and can then be inspected and properly handled in C++.

2. Using google3/third_party/clif/python/callback_exception_guard.py is an easier but also less safe fallback option (a random example: cl/537352397).

A great deal of effort was spent on reporting all essential information with the `LOG(FATAL)` activated by this CL. In most cases this is expected to point to all information needed for starting work on a forward fix. For example:

```
[ RUN      ] PyObjectPtrTest.test_call_callback_with_pyobject_ptr_arg
E0602 15:32:04.598630     592 runtime.cc:311] Python exception in call of clif::callback FOLLOWS (stderr):
@BEGIN(Python exception)

Traceback (most recent call last):
  File "/build/work/6985daf185a2c38e03451df32a9fa64d0080/google3/runfiles/google3/third_party/clif/testing/python/pyobject_ptr_test.py", line 63, in cb
    raise ValueError(f"Unknown pvh.value: {pvh.value}")
ValueError: Unknown pvh.value: 3.0

@END(Python exception)
E0602 15:32:04.599056     592 runtime.cc:318] repr(callable) FOLLOWS (stderr):
@BEGIN(Python repr)

<function PyObjectPtrTest.test_call_callback_with_pyobject_ptr_arg.<locals>.cb at 0x7fea63db6830>

@END(Python repr)
E0602 15:32:04.599108     592 runtime.cc:328] typeid(ReturnType).name(): N25clif_testing_pyobject_ptr14CppValueHolderE [HINT: http://demangle]
F0602 15:32:04.599134     592 stltypes.h:388] callback raised a Python exception (exception was sent to stderr). If this is simply a bug, please fix. If exceptions are expected, please use absl::Status / absl::StatusOr as return type (recommended) or google3/third_party/clif/python/callback_exception_guard.py (less safe) to handle them.
*** Check failure stack trace: ***
    @     0x563c4afd2109  absl::log_internal::LogMessage::SendToLog()
    @     0x563c4afd1876  absl::log_internal::LogMessage::Flush()
    @     0x563c4afd2569  absl::log_internal::LogMessageFatal::~LogMessageFatal()
    @     0x563c4a64df28  clif::callback::Func<>::operator()()
    @     0x563c4a64c14a  google3_third__party_clif_testing_python_pyobject__ptr_clifwrap::wrapcall_callback_with_pyobject_ptr_arg()
```

Concretely, look for this in the output of failing binaries:

* `Python exception in call of clif::callback FOLLOWS`

* `repr(callable)`

* `typeid(ReturnType).name()` ... HINT: http://demangle

PiperOrigin-RevId: 538261960