Undoing some changes in `add_proto_library`, based on guidance by @mkruskal-google
Error resolved by this change:

```
Traceback (most recent call last):
  File "/mounted_clif/clif/pyclif.py", line 35, in <module>
    from clif.protos import ast_pb2
ImportError: cannot import name 'ast_pb2' from 'clif.protos' (/build/clif/protos/__init__.py)
```