`clif_type_caster` declaration/definition safety.
This simple CL is a functional no-op, just to improve readability and safety:

* This CL makes it immediately obvious what combinations of `bool`s are expected and supported: only the ones for which there are explicit definitions.

* If future work accidentally leads to an unexpected combination of `bool`s, the compiler will produce an easily understandable error message, for example:

```
blaze-out/k8-asan-fastbuild/genfiles/third_party/clif/testing/python/type_caster_clif.cc:37:78: error: implicit instantiation of undefined template 'pybind11::detail::clif_type_caster<clif_testing::ValueHolderFromOnly>'
template <> struct type_caster<::clif_testing::ValueHolderFromOnly> : public clif_type_caster<::clif_testing::ValueHolderFromOnly>{};
                                                                             ^
./third_party/clif/pybind11/runtime.h:210:8: note: template is declared here
struct clif_type_caster;
       ^
```

Tested with this change in google3/devtools/clif/python/clif_build_rule.bzl:

```
-_GEN_PYBIND11 = False
+_GEN_PYBIND11 = True
```

Command:

```
blaze test //third_party/clif/... -k
```

* http://sponge2/fd84135e-a719-4ab8-92a9-ea750fb216ef

There are only expected failures (our current baseline):

```
//third_party/clif/testing/python:callback_test                 FAILED TO BUILD
//third_party/clif/examples/wrap_protos/python:wrap_protos_test          FAILED in 1.4s
//third_party/clif/testing/python:non_raising_test                       FAILED in 1.3s
//third_party/clif/testing/python:std_containers_str_bytes_test          FAILED in 1.1s
//third_party/clif/testing/python:t9_test                                FAILED in 1.3s
Executed 4 out of 117 tests: 112 tests pass, 1 fails to build and 4 fail remotely.
```

See also: https://github.com/google/pywrapcc/pull/30028  —  The first commit under this PR proves that the `clif_type_caster` approach works reliably on all platforms.

PiperOrigin-RevId: 525488414