Fixes for two breakages caused by internal changes.
1. `isPureVirtual` is only available in LLVM 18:

* https://github.com/llvm/llvm-project/pull/78463

```
/mounted_clif/clif/backend/matcher.cc: In member function 'const clang::FunctionDecl* clif::ClifMatcher::MatchAndSetFuncFromCandidates(const clif::ClifLookupResult&, clif::protos::FuncDecl*)':
/mounted_clif/clif/backend/matcher.cc:2740:51: error: 'const class clang::CXXMethodDecl' has no member named 'isPureVirtual'; did you mean 'isVirtual'?
 2740 |       func_decl->set_is_pure_virtual(method_decl->isPureVirtual());
      |                                                   ^~~~~~~~~~~~~
      |                                                   isVirtual
/mounted_clif/clif/backend/matcher.cc: In function 'const string clif::GetDeclNativeName(const clif::protos::Decl&)':
/mounted_clif/clif/backend/matcher.cc:92:1: warning: control reaches end of non-void function [-Wreturn-type]
   92 | }
      | ^
/mounted_clif/clif/backend/matcher.cc: In function 'std::string clif::GetErrorCodeString(clif::ClifErrorCode)':
/mounted_clif/clif/backend/matcher.cc:179:1: warning: control reaches end of non-void function [-Wreturn-type]
  179 | }
      | ^
```

2. `absl::StrCat(proto)` does not work as a replacement for `proto.DebugString()` with the versions of abseil-cpp (20230125.1) and protobuf (22.0) currently used for GitHub testing:

```
/usr/bin/ld: libclifMatcher.a(matcher.cc.o): in function `void google::protobuf::AbslStringify<absl::lts_20230125::strings_internal::StringifySink>(absl::lts_20230125::strings_internal::StringifySink&, google::protobuf::Message const&)':
matcher.cc:(.text._ZN6google8protobuf13AbslStringifyIN4absl12lts_2023012516strings_internal13StringifySinkEEEvRT_RKNS0_7MessageE[_ZN6google8protobuf13AbslStringifyIN4absl12lts_2023012516strings_internal13StringifySinkEEEvRT_RKNS0_7MessageE]+0x51): undefined reference to `google::protobuf::internal::PerformAbslStringify(google::protobuf::Message const&, absl::lts_20230125::FunctionRef<void (absl::lts_20230125::string_view)>)'
collect2: error: ld returned 1 exit status
```

GitHub testing (in combination with child cl/598975069): https://github.com/google/clif/pull/87

PiperOrigin-RevId: 600506085